[package]
name = "synapos"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9"


[build-dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
default = []

[workspace]


[[bin]]
name = "synapos"
path = "src/main.rs"
test = false
doc = false
